### ISSUE TITLE
有線でロボットを動かせるようにする。

### ISSUE THREAD

**Issue by tinjyuu** [kabuku/makerfaire-tokyo-2018#53]
Lanケーブルで接続してしまえば、既存のロボットのコードのままで動くはずなので、その方向性で行きたいです。

ラズパイ零には、lanのポートはないので、usbに変換して接続する予定です。
macとラズパイをlanケーブルで繋いで通信できるかは要検証。

**Comment by soundTricker** [comment]
一応やったことはあるので問題なくできるはずです。LAN→USB変換ケーブル持ってるので、火曜日に渡しますよ

**Comment by soundTricker** [comment]
なお、macでちょい設定必要なのと、raspiのip探すのがめんどくさかったります。

**Comment by kimamula** [comment]
やらない
